- environment:
    x: 8.0
    y: 8.0
    start_point:
      x: 0.0
      y: 0.0
    end_point:
      x: 8.0
      y: 8.0
    obstacles:
      - - x: 0.5
          y: 2.0
        - x: 0.5
          y: 5.0
        - x: 2.0
          y: 5.0
      - - x: 1.0
          y: 2.0
        - x: 0.5
          y: 2.0
        - x: 2.0
          y: 5.0
      - - x: 3.0
          y: 0.5
        - x: 6.0
          y: 0.5
        - x: 3.0
          y: 1.5
      - - x: 3.0
          y: 1.5
        - x: 6.0
          y: 1.5
        - x: 6.0
          y: 0.5
      - - x: 3.5
          y: 4.5
        - x: 5.5
          y: 4.5
        - x: 4.0
          y: 3.0
      - - x: 6.0
          y: 3.0
        - x: 5.5
          y: 4.5
        - x: 4.0
          y: 3.0
      - - x: 6.0
          y: 5.5
        - x: 6.0
          y: 7.0
        - x: 6.5
          y: 7.0
      - - x: 6.0
          y: 5.5
        - x: 7.0
          y: 5.5
        - x: 6.5
          y: 7.0