- environment:
    x: 20.0
    y: 15.0
    start_point:
      x: 2.0
      y: 2.0
    end_point:
      x: 18.0
      y: 13.0
    obstacles:
      - - x: 5.0
          y: 5.0
        - x: 8.0
          y: 5.0
        - x: 6.5
          y: 7.0
      - - x: 10.0
          y: 10.0
        - x: 14.0
          y: 10.0
        - x: 12.0
          y: 12.0
      - - x: 16.0
          y: 3.0
        - x: 18.0
          y: 3.0
        - x: 17.0
          y: 5.0