- environment:
    x: 10.0
    y: 10.0
    start_point:
      x: 0.5
      y: 0.5
    end_point:
      x: 9.5
      y: 9.5
    obstacles:
      - - x: 1.0
          y: 1.0
        - x: 2.0
          y: 1.0
        - x: 1.5
          y: 2.0
      - - x: 8.0
          y: 8.0
        - x: 9.0
          y: 8.0
        - x: 8.5
          y: 9.0
      - - x: 4.0
          y: 4.0
        - x: 8.0
          y: 4.0
        - x: 6.0
          y: 5.0
      - - x: 10.0
          y: 6.0
        - x: 10.0
          y: 5.0
        - x: 3.0
          y: 8.0
      - - x: 1.0
          y: 1.0
        - x: 0.0
          y: 2.0
        - x: 1.5
          y: 2.0
      - - x: 3.0
          y: 3.0
        - x: 10.0
          y: 0.0
        - x: 10.0
          y: 1.0
      - - x: 0.0
          y: 10.0
        - x: 2.0
          y: 3.0
        - x: 1.0
          y: 10.0
      - - x: 2.0
          y: 7.0
        - x: 5.0
          y: 6.0
        - x: 3.0
          y: 4.0