- environment:
    x: 10.0
    y: 10.0
    start_point:
      x: 0.5
      y: 0.5
    end_point:
      x: 9.5
      y: 9.5
    obstacles:
      - - x: 1.0
          y: 1.0
        - x: 2.0
          y: 1.0
        - x: 1.5
          y: 2.0
      - - x: 8.0
          y: 8.0
        - x: 9.0
          y: 8.0
        - x: 8.5
          y: 9.0
      - - x: 4.0
          y: 4.0
        - x: 8.0
          y: 4.0
        - x: 6.0
          y: 5.0
      - - x: 10.0
          y: 6.0
        - x: 10.0
          y: 5.0
        - x: 3.0
          y: 8.0
      - - x: 1.0
          y: 1.0
        - x: 0.0
          y: 2.0
        - x: 1.5
          y: 2.0
      - - x: 3.0
          y: 3.0
        - x: 10.0
          y: 0.0
        - x: 10.0
          y: 1.0
      - - x: 0.0
          y: 10.0
        - x: 2.0
          y: 3.0
        - x: 1.0
          y: 10.0

- environment:
    x: 10.0
    y: 10.0
    start_point:
      x: 1.0
      y: 1.0
    end_point:
      x: 9.0
      y: 9.0
    obstacles:
      - - x: 2.0
          y: 2.0
        - x: 3.0
          y: 2.0
        - x: 2.5
          y: 3.0
      - - x: 5.0
          y: 5.0
        - x: 6.0
          y: 5.0
        - x: 5.5
          y: 6.0

- environment:
    x: 15.0
    y: 8.0
    start_point:
      x: 2.0
      y: 1.0
    end_point:
      x: 13.0
      y: 7.0
    obstacles:
      - - x: 4.0
          y: 3.0
        - x: 6.0
          y: 3.0
        - x: 5.0
          y: 4.5
      - - x: 8.0
          y: 6.0
        - x: 10.0
          y: 6.0
        - x: 9.0
          y: 7.5
      - - x: 12.0
          y: 2.0
        - x: 13.0
          y: 2.0
        - x: 12.5
          y: 3.0

- environment:
    x: 20.0
    y: 15.0
    start_point:
      x: 2.0
      y: 2.0
    end_point:
      x: 18.0
      y: 13.0
    obstacles:
      - - x: 5.0
          y: 5.0
        - x: 8.0
          y: 5.0
        - x: 6.5
          y: 7.0
      - - x: 10.0
          y: 10.0
        - x: 14.0
          y: 10.0
        - x: 12.0
          y: 12.0
      - - x: 16.0
          y: 3.0
        - x: 18.0
          y: 3.0
        - x: 17.0
          y: 5.0

- environment:
    x: 10.0
    y: 10.0
    start_point:
      x: 0.25
      y: 5.0
    end_point:
      x: 9.75
      y: 5.0
    obstacles:
      - - x: 0.0
          y: 10.0
        - x: 0.5
          y: 4.5
        - x: 1.0
          y: 10.0
      - - x: 1.0
          y: 10.0
        - x: 1.5
          y: 4.5
        - x: 2.0
          y: 10.0
      - - x: 2.0
          y: 10.0
        - x: 2.5
          y: 4.5
        - x: 3.0
          y: 10.0
      - - x: 3.0
          y: 10.0
        - x: 3.5
          y: 4.5
        - x: 4.0
          y: 10.0
      - - x: 4.0
          y: 10.0
        - x: 4.5
          y: 4.5
        - x: 5.0
          y: 10.0
      - - x: 5.0
          y: 10.0
        - x: 5.5
          y: 4.5
        - x: 6.0
          y: 10.0
      - - x: 6.0
          y: 10.0
        - x: 6.5
          y: 4.5
        - x: 7.0
          y: 10.0
      - - x: 7.0
          y: 10.0
        - x: 7.5
          y: 4.5
        - x: 8.0
          y: 10.0
      - - x: 8.0
          y: 10.0
        - x: 8.5
          y: 4.5
        - x: 9.0
          y: 10.0
      - - x: 9.0
          y: 10.0
        - x: 9.5
          y: 4.5
        - x: 10.0
          y: 10.0
      - - x: 0.5
          y: 0.0
        - x: 1.0
          y: 5.5
        - x: 1.5
          y: 0.0
      - - x: 1.5
          y: 0.0
        - x: 2.0
          y: 5.5
        - x: 2.5
          y: 0.0
      - - x: 2.5
          y: 0.0
        - x: 3.0
          y: 5.5
        - x: 3.5
          y: 0.0
      - - x: 3.5
          y: 0.0
        - x: 4.0
          y: 5.5
        - x: 4.5
          y: 0.0
      - - x: 4.5
          y: 0.0
        - x: 5.0
          y: 5.5
        - x: 5.5
          y: 0.0
      - - x: 5.5
          y: 0.0
        - x: 6.0
          y: 5.5
        - x: 6.5
          y: 0.0
      - - x: 6.5
          y: 0.0
        - x: 7.0
          y: 5.5
        - x: 7.5
          y: 0.0
      - - x: 7.5
          y: 0.0
        - x: 8.0
          y: 5.5
        - x: 8.5
          y: 0.0
      - - x: 8.5
          y: 0.0
        - x: 9.0
          y: 5.5
        - x: 9.5
          y: 0.0